# Generated by Django 4.1.2 on 2022-12-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificaddor de la voleta')),
                ('fechaEmisionBoleta', models.DateTimeField(auto_now_add=True)),
                ('valorDeLaCita', models.IntegerField(verbose_name='Valor de la cita')),
                ('comisionDelMedico', models.IntegerField()),
            ],
        ),
    ]
