# Generated by Django 4.1.2 on 2022-12-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMedica', '0004_delete_boleta_alter_cita_duracioncita_and_more'),
        ('appSecretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='cita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='appMedica.cita'),
        ),
    ]
