# Generated by Django 4.1.2 on 2022-12-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSecretaria', '0002_boleta_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='idBoleta',
        ),
        migrations.AddField(
            model_name='boleta',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
