# Generated by Django 4.1.2 on 2022-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSecretaria', '0003_remove_boleta_idboleta_boleta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fechaEmisionBoleta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
