# Generated by Django 4.1.2 on 2022-12-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMedica', '0005_alter_cita_fechacita'),
        ('appSecretaria', '0004_alter_boleta_fechaemisionboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='appMedica.medico'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='comisionDelMedico',
            field=models.IntegerField(verbose_name='Porcentaje que se lleva el médico'),
        ),
    ]
