# Generated by Django 4.1.2 on 2022-11-23 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMedica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('rutUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='rut(sin digito verificador)')),
                ('dvUsuario', models.CharField(max_length=1, verbose_name='digito verificador')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellidoUsuario', models.CharField(max_length=30, verbose_name='apellido')),
                ('direccionUsuario', models.CharField(max_length=40, verbose_name='dirrecion')),
                ('telefonoUsuario', models.CharField(max_length=12, verbose_name='telefono celular')),
                ('mailUsuario', models.EmailField(max_length=40, verbose_name='email')),
                ('especialidadUsuario', models.ForeignKey(choices=[(1, 'Cardiología'), (2, 'Cirugía general'), (3, 'Dermatología')], default='Dermatología', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appMedica.especialidad', verbose_name='especialidad del medico')),
                ('rolUsuario', models.ForeignKey(choices=[(1, 'Paciente'), (2, 'Médico'), (3, 'Secretaria'), (4, 'Administrador')], default='Paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='appMedica.rol', verbose_name='rol del usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateTimeField()),
                ('horaInicioCita', models.TimeField(choices=[('0', 'seleccione una opción'), ('1', '0:00'), ('2', '1:00'), ('3', '2:00'), ('4', '3:00'), ('5', '4:00'), ('6', '5:00'), ('7', '6:00'), ('8', '7:00'), ('9', '8:00'), ('10', '9:00'), ('11', '10:00'), ('12', '11:00'), ('13', '12:00'), ('14', '13:00'), ('15', '14:00'), ('16', '15:00'), ('17', '16:00'), ('18', '17:00'), ('19', '18:00'), ('20', '19:00'), ('21', '20:00'), ('22', '21:00'), ('23', '22:00'), ('24', '23:00')], default=0)),
                ('duracionCita', models.IntegerField(choices=[('0', 'seleccione una opción'), ('1', '15 minutos'), ('2', '30 minutos'), ('3', '45 minutos'), ('4', '60 minutos')], default=0)),
                ('medicoCita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicoCita', to='appMedica.perfil')),
                ('pacienteCita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pacienteCita', to='appMedica.perfil')),
            ],
        ),
    ]
