# Generated by Django 4.1.2 on 2022-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMedica', '0004_delete_boleta_alter_cita_duracioncita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(verbose_name='fecha de la cita'),
        ),
    ]
